version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brainagriculture_api
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=brainagriculture
      - JWT_SECRET=brainagriculture
    depends_on:
      - database
    volumes:
      - .:/usr/src/app
    command: npm run start:dev

  database:
    image: postgres:15
    container_name: brainagriculture_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brainagriculture
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
